{
 "title": "DailyTracker Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Informs how long has the application been up.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"DailyTracker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"DailyTracker\", uri!~\"/actuator/.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"DailyTracker\", status=~\"5..\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (JVM Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"DailyTracker\", area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Latency per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum{application=\"DailyTracker\", uri!~\"/actuator/.*\"}[5m])) \r\n/ \r\nsum by (uri) (rate(http_server_requests_seconds_count{application=\"DailyTracker\", uri!~\"/actuator/.*\"}[5m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Logs volume per level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({app=\"DailyTracker\"}[$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs live stream",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"DailyTracker\", level=~\"WARN|ERROR\"}"
    }
   ]
  }
 ]
}